services:
  api:
    build: 
      context: go/
      dockerfile: dockerfile
    working_dir: /api
    ports:
      - "9000:9000"
    environment:
      FRONT_URL: "http://localhost:3000"
  web:
    build:
      context: typescript/simple-mercari-web/
      dockerfile: dockerfile
    working_dir: /web
    ports:
      - "3000:3000"
    environment: 
      REACT_APP_API_URL: "http://localhost:9000"
