FROM golang:1.21.7-alpine
WORKDIR /app

RUN addgroup -S mercari && adduser -S trainee -G mercari

# Goのパッケージをインストール
RUN apk add --no-cache go gcc musl-dev

WORKDIR /app
COPY . /app/go
COPY db /app/db
RUN chown -R trainee:mercari /app/db

WORKDIR /app/go
RUN go mod tidy

EXPOSE 9000

CMD go run app/main.go
