FROM golang:1.21-alpine
WORKDIR /app

# Goのパッケージをインストール
RUN apk add --no-cache go gcc musl-dev

COPY . .
COPY go.mod go.sum ./
RUN go mod download
COPY db/ ./db/
RUN go mod tidy

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /go

EXPOSE 9000

CMD ["go", "run", "app/main.go"]
