FROM golang:1.21.7-alpine
WORKDIR /api

#  Goのパッケージをインストール
RUN apk update && apk add --no-cache go gcc musl-dev

COPY . .

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /api

RUN go mod tidy

USER trainee

EXPOSE 9000

CMD ["go", "run", "app/main.go"]

