FROM node:20-alpine
WORKDIR /web

COPY . .

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /web
RUN npm install
RUN npm ci

USER trainee

EXPOSE 3000

CMD ["npm", "start"]
